version: '3.1'  
services:
  dicom:
    build: dicom/
    env_file:
      - ./dicom/config/.env
    command: python start.py
    expose:
      - '5000'
    ports:
      - 5000:5000
    networks:
      - dicomnet
    volumes:
      - ./logs/dicom:/app/logs
    depends_on:
      - orthanc
      - localrabbit
  mrstudy:
    build: mr_study/
    restart: unless-stopped
    env_file:
      - ./mr_study/config/.env
    command: python general.py
    networks:
      - dicomnet
    volumes:
      - ./logs/mr_study:/app/logs
    depends_on:
      - orthanc
      - localrabbit
      - localdb
  orthanc:
    image: jodogne/orthanc-plugins:1.11.0
    command: /run/secrets/  # Path to the configuration files (stored as secrets)
    ports:
      - 4242:4242
      - 8042:8042
    secrets:
      - orthanc.json
    networks:
      - dicomnet
    hostname: orthanchost
    environment:
      - ORTHANC_NAME=Dicomnet
  localrabbit:
    image: rabbitmq:management
    hostname: rabbithost
    networks:
      - dicomnet
    ports:
      - 15672:15672
  localdb:
    image: mysql
    hostname: dbhost
    networks:
      - dicomnet
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - dicomnet

secrets:
  orthanc.json:
    file: orthanc.json

networks:
  dicomnet:
    driver: bridge